### ISSUE TITLE
PowerShell Preview extension

### ISSUE THREAD

**Issue by andrewtchilds** [gep13/chocolatey-vscode#68]
Chocolatey takes a dependency on the PowerShell extension, so VS Code throws an error when you try to disable it in lieu of the newly released [PowerShell Preview](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) extension.

Not sure if it's possible to do in VS Code's extension manifest, but it would be nice to be able to run the Chocolatey extension alongside the PowerShell Preview extension.

**Comment by gep13** [comment]
@andrewtchilds thanks for raising this issue!  I wasn't aware of that extension.  I will try to figure out if there is a way of supporting both, and if not, I will likely remove the dependency so that either can be used.

Can you provide more details about how exactly the error is shown when trying to so what you are doing?  Perhaps with a screenshot?

**Comment by andrewtchilds** [comment]
Thanks @gep13!

Here's the error that I get when I try to disable the PowerShell extension:
![image](https://user-images.githubusercontent.com/17715542/51789595-d6b79800-214f-11e9-8e60-9abb47b64f9f.png)

**Comment by gep13** [comment]
@andrewtchilds If you update to 0.7.0 of the Chocolatey VSCode Extension, you should be able to disable the PowerShell Extension.

Let me know if you still have issues.

**Comment by andrewtchilds** [comment]
Looks good, thanks again @gep13!

**Comment by gep13** [comment]
>@andrewtchilds said...
thanks again

You are very welcome!
